import { PersonaData, Product, RoutineStep } from './types';

export const PERSONAS: Record<string, PersonaData> = {
  combination: {
    label: 'Combination · mild dehydration',
    name: 'Sofía',
    concerns: ['Dehydration', 'Occasional breakouts', 'Uneven tone'],
    hydration: 64,
    barrier: 78,
    tone: 52,
    hero: 'Your skin is reading a touch thirsty this morning.',
    today: "Lead with a humectant serum before SPF. I'd skip the acid tonight — barrier's still rebuilding from Tuesday.",
    ritualCopy: 'A gentle morning. Aloe, hyaluronic, mineral SPF.',
    aiCoach: '"Your combination skin responds best to layering lightweight hydration — try pressing serum into slightly damp skin for 40% better absorption."',
  },
  oily: {
    label: 'Oily · reactive T-zone',
    name: 'Mateo',
    concerns: ['Excess sebum', 'Enlarged pores', 'Post-acne marks'],
    hydration: 71,
    barrier: 62,
    tone: 48,
    hero: 'Sebum is up 12% vs. your weekly baseline.',
    today: 'Niacinamide + a light zinc layer. Double cleanse tonight — yesterday\'s SPF was a heavy one.',
    ritualCopy: 'Balance the T-zone. Niacinamide, BHA, gel moisturizer.',
    aiCoach: '"Oily skin still needs hydration — skipping moisturizer signals your skin to produce even more sebum. A gel-water formula is your best bet."',
  },
  dry: {
    label: 'Dry · sensitized',
    name: 'Lena',
    concerns: ['Dryness', 'Tightness', 'Redness on cheeks'],
    hydration: 41,
    barrier: 55,
    tone: 68,
    hero: "Barrier's a little tender — let's keep it quiet today.",
    today: 'Ceramide cream on damp skin, SPF, nothing acidic. One product less is more today.',
    ritualCopy: 'Repair mode. Ceramides, squalane, rich cream.',
    aiCoach: '"Apply your ceramide cream within 60 seconds of cleansing while skin is still damp — you\'ll lock in significantly more moisture."',
  },
  mature: {
    label: 'Mature · firmness focus',
    name: 'Camila',
    concerns: ['Fine lines', 'Loss of firmness', 'Dehydration'],
    hydration: 58,
    barrier: 82,
    tone: 61,
    hero: 'Retinal night went well — firmness is trending up 4%.',
    today: 'Peptide serum, a generous moisturizer, and SPF 50. Retinal returns Thursday.',
    ritualCopy: 'Lift & protect. Peptides, vitamin C, SPF 50.',
    aiCoach: '"Peptides work best when given time to absorb — wait 3–5 minutes before layering your moisturizer for maximum firming effect."',
  },
};

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    brand: 'La Roche-Posay',
    name: 'Hyalu B5 Serum',
    type: 'Serum',
    size: '30ml',
    img: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=70',
    steps: ['AM', 'PM'],
    tag: 'Hydrating',
    opened: 'Mar 12',
    match: 96,
    verdict: 'Excellent fit for your skin profile. The hyaluronic acid complex targets your hydration deficit while the B5 supports barrier recovery.',
    ingredients: [
      { name: 'Hyaluronic Acid', reason: 'Multi-weight, penetrates deeply', tone: 'good' },
      { name: 'Vitamin B5', reason: 'Barrier-supporting panthenol', tone: 'good' },
      { name: 'Madecassoside', reason: 'Gentle soothing actives', tone: 'good' },
    ],
  },
  {
    id: 'p2',
    brand: 'The Ordinary',
    name: 'Niacinamide 10%',
    type: 'Serum',
    size: '60ml',
    img: 'https://images.unsplash.com/photo-1631730359585-38a4935cbec4?w=600&q=70',
    steps: ['AM'],
    tag: 'Balancing',
    opened: 'Feb 02',
    match: 88,
    verdict: 'Strong fit for sebum control and pore clarity. Use in the AM under SPF for best results.',
    ingredients: [
      { name: 'Niacinamide 10%', reason: 'Regulates sebum production', tone: 'good' },
      { name: 'Zinc PCA', reason: 'Antibacterial, reduces congestion', tone: 'good' },
      { name: 'Propanediol', reason: 'Solvent, generally well tolerated', tone: 'neutral' },
    ],
  },
  {
    id: 'p3',
    brand: 'CeraVe',
    name: 'Moisturizing Cream',
    type: 'Moisturizer',
    size: '340g',
    img: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=70',
    steps: ['AM', 'PM'],
    tag: 'Repair',
    opened: 'Jan 28',
    match: 91,
    verdict: 'Ideal barrier repair formula. The ceramide trio matches your skin\'s natural lipid profile closely.',
    ingredients: [
      { name: 'Ceramide NP/AP/EOP', reason: 'Matches skin lipid ratios', tone: 'good' },
      { name: 'Hyaluronic Acid', reason: 'Draws moisture to the surface', tone: 'good' },
      { name: 'Niacinamide', reason: 'Gentle brightening benefit', tone: 'good' },
    ],
  },
  {
    id: 'p4',
    brand: 'Isdin',
    name: 'Fotoprotector 50+',
    type: 'Sunscreen',
    size: '50ml',
    img: 'https://images.unsplash.com/photo-1556228852-80b6e5eeff06?w=600&q=70',
    steps: ['AM'],
    tag: 'Mineral SPF',
    opened: 'Mar 30',
    match: 94,
    verdict: 'Top-rated for your profile. Lightweight enough for daily use without clogging pores.',
    ingredients: [
      { name: 'Zinc Oxide 22%', reason: 'Broad-spectrum mineral filter', tone: 'good' },
      { name: 'Iron Oxides', reason: 'Protects from visible light', tone: 'good' },
      { name: 'Glycerin', reason: 'Humectant, helps application', tone: 'good' },
    ],
  },
  {
    id: 'p5',
    brand: "Paula's Choice",
    name: '2% BHA Liquid',
    type: 'Exfoliant',
    size: '118ml',
    img: 'https://images.unsplash.com/photo-1612532774233-4086ab0c9f7f?w=600&q=70',
    steps: ['PM'],
    tag: 'Exfoliating',
    opened: 'Dec 04',
    match: 72,
    verdict: 'Use with caution — limit to 2x per week and skip on barrier-repair nights.',
    ingredients: [
      { name: 'Salicylic Acid 2%', reason: 'Unclogs pores, exfoliates', tone: 'good' },
      { name: 'Methylpropanediol', reason: 'Penetration enhancer', tone: 'neutral' },
      { name: 'Fragrance', reason: 'Low, but worth monitoring', tone: 'warn' },
    ],
  },
  {
    id: 'p6',
    brand: 'Byoma',
    name: 'Creamy Jelly Cleanser',
    type: 'Cleanser',
    size: '175ml',
    img: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=70',
    steps: ['AM', 'PM'],
    tag: 'Gentle',
    opened: 'Mar 01',
    match: 90,
    verdict: 'Excellent everyday cleanser. Barrier-protecting formula won\'t strip your skin before actives.',
    ingredients: [
      { name: 'Ceramides', reason: 'Protects barrier during cleanse', tone: 'good' },
      { name: 'Glycerin', reason: 'Maintains hydration post-cleanse', tone: 'good' },
      { name: 'Betaine', reason: 'Mild surfactant complex', tone: 'good' },
    ],
  },
];

export const ROUTINE_STEPS: Record<string, RoutineStep[]> = {
  AM: [
    { id: 'am1', step: 'Cleanse', product: 'Creamy Jelly Cleanser', brand: 'Byoma', time: '1 min', done: false, productId: 'p6' },
    { id: 'am2', step: 'Treat', product: 'Hyalu B5 Serum', brand: 'La Roche-Posay', time: '2 min dry-down', done: false, productId: 'p1' },
    { id: 'am3', step: 'Balance', product: 'Niacinamide 10%', brand: 'The Ordinary', time: '1 min', done: false, productId: 'p2' },
    { id: 'am4', step: 'Moisturize', product: 'Moisturizing Cream', brand: 'CeraVe', time: '1 min', done: false, productId: 'p3' },
    { id: 'am5', step: 'Protect', product: 'Fotoprotector 50+', brand: 'Isdin', time: '2 min', done: false, productId: 'p4' },
  ],
  PM: [
    { id: 'pm1', step: 'First cleanse', product: 'Creamy Jelly Cleanser', brand: 'Byoma', time: '1 min', done: false, productId: 'p6' },
    { id: 'pm2', step: 'Exfoliate', product: '2% BHA Liquid', brand: "Paula's Choice", time: '10 min', done: false, productId: 'p5' },
    { id: 'pm3', step: 'Treat', product: 'Hyalu B5 Serum', brand: 'La Roche-Posay', time: '2 min dry-down', done: false, productId: 'p1' },
    { id: 'pm4', step: 'Seal', product: 'Moisturizing Cream', brand: 'CeraVe', time: '1 min', done: false, productId: 'p3' },
  ],
};
